apiVersion: v1
data:
  GLUU_CONFIG_ADAPTER: kubernetes
  GLUU_CONFIG_KUBERNETES_NAMESPACE: gluu
  GLUU_CONTAINER_METADATA: kubernetes
  GLUU_LDAP_URL: opendj:1636
  GLUU_PERSISTENCE_LDAP_MAPPING: ""
  GLUU_PERSISTENCE_TYPE: ldap
  GLUU_SECRET_ADAPTER: kubernetes
  GLUU_SECRET_KUBERNETES_NAMESPACE: gluu
kind: ConfigMap
metadata:
  labels:
    app: ldap-cache-cleaner
  name: ldap-cache-cleaner-cm-9c9754kb7h
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ldap-cache-cleaner
  name: ldap-cache-cleaner
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: ldap-cache-cleaner
    spec:
      template:
        metadata:
          labels:
            app: ldap-cache-cleaner
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: ldap-cache-cleaner-cm-9c9754kb7h
            image: abudayyehwork/ldap-cache-cleaner:4.1.1_dev
            name: ldap-cache-cleaner
          restartPolicy: Never
  schedule: '*/1 * * * *'